### ISSUE TITLE
the meaning of getWidthOfSpace()

### ISSUE THREAD

**Issue by BlackFlying** [neumino/PDF-to-standard-HTML#1]
(pdfbox )getWidthOfSpace():This will get the width of a space character.

I donnt know what does this mean.And what does the WidthOfSpace relate with? 

example:
font                                                                                               WidthOfSpace()  
PDType0Font/PDCIDFontType0 RALYRS+AdobeSongStd-Light    6.0 
PDType0Font/PDCIDFontType0 RALYRS+AdobeSongStd-Light    7.0

**Comment by neumino** [comment]
It represents how big a space character will be.
You should ask this kind of question to pdfbox... 
https://pdfbox.apache.org/support.html
